#############################################################################
# Makefile for building: quvcview
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 12? 20 15:52:18 2015
# Project:  quvcview.pro
# Template: app
# Command: /opt/qt4.7.3/bin/qmake -o Makefile quvcview.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-fsl-linux-gnueabi-gcc
CXX           = arm-fsl-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt4.7.3/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I/opt/qt4.7.3/include/QtCore -I/opt/qt4.7.3/include/QtNetwork -I/opt/qt4.7.3/include/QtGui -I/opt/qt4.7.3/include -I. -I.
LINK          = arm-fsl-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt4.7.3/lib
LIBS          = $(SUBLIBS)  -L/opt/qt4.7.3/lib -lQtGui -L/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/lib -L/opt/qt4.7.3/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-fsl-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /opt/qt4.7.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-fsl-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		quvcview.cpp \
		v4l2.c \
		yuv422_rgb.c moc_quvcview.cpp
OBJECTS       = main.o \
		quvcview.o \
		v4l2.o \
		yuv422_rgb.o \
		moc_quvcview.o
DIST          = /opt/qt4.7.3/mkspecs/common/g++.conf \
		/opt/qt4.7.3/mkspecs/common/unix.conf \
		/opt/qt4.7.3/mkspecs/common/linux.conf \
		/opt/qt4.7.3/mkspecs/common/qws.conf \
		/opt/qt4.7.3/mkspecs/qconfig.pri \
		/opt/qt4.7.3/mkspecs/features/qt_functions.prf \
		/opt/qt4.7.3/mkspecs/features/qt_config.prf \
		/opt/qt4.7.3/mkspecs/features/exclusive_builds.prf \
		/opt/qt4.7.3/mkspecs/features/default_pre.prf \
		/opt/qt4.7.3/mkspecs/features/release.prf \
		/opt/qt4.7.3/mkspecs/features/default_post.prf \
		/opt/qt4.7.3/mkspecs/features/warn_on.prf \
		/opt/qt4.7.3/mkspecs/features/qt.prf \
		/opt/qt4.7.3/mkspecs/features/unix/thread.prf \
		/opt/qt4.7.3/mkspecs/features/moc.prf \
		/opt/qt4.7.3/mkspecs/features/resources.prf \
		/opt/qt4.7.3/mkspecs/features/uic.prf \
		/opt/qt4.7.3/mkspecs/features/yacc.prf \
		/opt/qt4.7.3/mkspecs/features/lex.prf \
		/opt/qt4.7.3/mkspecs/features/include_source_dir.prf \
		quvcview.pro
QMAKE_TARGET  = quvcview
DESTDIR       = 
TARGET        = quvcview

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_quvcview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: quvcview.pro  /opt/qt4.7.3/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf /opt/qt4.7.3/mkspecs/common/g++.conf \
		/opt/qt4.7.3/mkspecs/common/unix.conf \
		/opt/qt4.7.3/mkspecs/common/linux.conf \
		/opt/qt4.7.3/mkspecs/common/qws.conf \
		/opt/qt4.7.3/mkspecs/qconfig.pri \
		/opt/qt4.7.3/mkspecs/features/qt_functions.prf \
		/opt/qt4.7.3/mkspecs/features/qt_config.prf \
		/opt/qt4.7.3/mkspecs/features/exclusive_builds.prf \
		/opt/qt4.7.3/mkspecs/features/default_pre.prf \
		/opt/qt4.7.3/mkspecs/features/release.prf \
		/opt/qt4.7.3/mkspecs/features/default_post.prf \
		/opt/qt4.7.3/mkspecs/features/warn_on.prf \
		/opt/qt4.7.3/mkspecs/features/qt.prf \
		/opt/qt4.7.3/mkspecs/features/unix/thread.prf \
		/opt/qt4.7.3/mkspecs/features/moc.prf \
		/opt/qt4.7.3/mkspecs/features/resources.prf \
		/opt/qt4.7.3/mkspecs/features/uic.prf \
		/opt/qt4.7.3/mkspecs/features/yacc.prf \
		/opt/qt4.7.3/mkspecs/features/lex.prf \
		/opt/qt4.7.3/mkspecs/features/include_source_dir.prf \
		/opt/qt4.7.3/lib/libQtGui.prl \
		/opt/qt4.7.3/lib/libQtNetwork.prl \
		/opt/qt4.7.3/lib/libQtCore.prl
	$(QMAKE) -o Makefile quvcview.pro
/opt/qt4.7.3/mkspecs/common/g++.conf:
/opt/qt4.7.3/mkspecs/common/unix.conf:
/opt/qt4.7.3/mkspecs/common/linux.conf:
/opt/qt4.7.3/mkspecs/common/qws.conf:
/opt/qt4.7.3/mkspecs/qconfig.pri:
/opt/qt4.7.3/mkspecs/features/qt_functions.prf:
/opt/qt4.7.3/mkspecs/features/qt_config.prf:
/opt/qt4.7.3/mkspecs/features/exclusive_builds.prf:
/opt/qt4.7.3/mkspecs/features/default_pre.prf:
/opt/qt4.7.3/mkspecs/features/release.prf:
/opt/qt4.7.3/mkspecs/features/default_post.prf:
/opt/qt4.7.3/mkspecs/features/warn_on.prf:
/opt/qt4.7.3/mkspecs/features/qt.prf:
/opt/qt4.7.3/mkspecs/features/unix/thread.prf:
/opt/qt4.7.3/mkspecs/features/moc.prf:
/opt/qt4.7.3/mkspecs/features/resources.prf:
/opt/qt4.7.3/mkspecs/features/uic.prf:
/opt/qt4.7.3/mkspecs/features/yacc.prf:
/opt/qt4.7.3/mkspecs/features/lex.prf:
/opt/qt4.7.3/mkspecs/features/include_source_dir.prf:
/opt/qt4.7.3/lib/libQtGui.prl:
/opt/qt4.7.3/lib/libQtNetwork.prl:
/opt/qt4.7.3/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile quvcview.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/quvcview1.0.0 || $(MKDIR) .tmp/quvcview1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/quvcview1.0.0/ && $(COPY_FILE) --parents quvcview.h v4l2.h yuv422_rgb.h .tmp/quvcview1.0.0/ && $(COPY_FILE) --parents main.cpp quvcview.cpp v4l2.c yuv422_rgb.c .tmp/quvcview1.0.0/ && $(COPY_FILE) --parents quvcview.ui .tmp/quvcview1.0.0/ && (cd `dirname .tmp/quvcview1.0.0` && $(TAR) quvcview1.0.0.tar quvcview1.0.0 && $(COMPRESS) quvcview1.0.0.tar) && $(MOVE) `dirname .tmp/quvcview1.0.0`/quvcview1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/quvcview1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_quvcview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_quvcview.cpp
moc_quvcview.cpp: v4l2.h \
		quvcview.h
	/opt/qt4.7.3/bin/moc $(DEFINES) $(INCPATH) quvcview.h -o moc_quvcview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_quvcview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_quvcview.h
ui_quvcview.h: quvcview.ui
	/opt/qt4.7.3/bin/uic quvcview.ui -o ui_quvcview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp quvcview.h \
		v4l2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

quvcview.o: quvcview.cpp quvcview.h \
		v4l2.h \
		ui_quvcview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quvcview.o quvcview.cpp

v4l2.o: v4l2.c v4l2.h \
		yuv422_rgb.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o v4l2.o v4l2.c

yuv422_rgb.o: yuv422_rgb.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o yuv422_rgb.o yuv422_rgb.c

moc_quvcview.o: moc_quvcview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quvcview.o moc_quvcview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

